(ns advanced-mechanics.unhygienic-2)

(defmacro squares [xs]
  `(map (fn [~'x] (* ~'x ~'x)) ~xs))

(println "Evaluating `(squares (range 10))` now works!")
(println)
(println (squares (range 10)))
(println)
(println "The expression `(* x x) produces")
(println)
(println `(* x x ))
(println)
(println "In this result, x is a variable in the **current** namespace.")
(println "Evaluating the expression `(* 'x 'x) returns")
(println)
(println `(* 'x 'x))
(println)
(println "In this result, the arguments are the quoted symbol `x` in the current namespace.")
(println "Finally, evaluating the expression `(* ~'x ~'x) returns")
(println)
(println `(* ~'x ~'x))
(println)
(println "The `~` will **unquote** the next form. Thus, the resulting expression")
(println "contains two symbols, `x`, in a local namespace. This result is what we want")
(println "in our macro expansion.")
(println)
(println (macroexpand `(squares (range 10))))
